version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "weekly" # daily, weekly, or monthly
      day: "monday"
      time: "08:00"
      timezone: "Europe/Lisbon"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated-pr"
